# Generated by Django 2.1.7 on 2019-02-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=10)),
                ('price', models.TextField(max_length=10)),
            ],
        ),
    ]
